-- =========================================================================
-- SKEMA SQL SUPABASE LENGKAP 5 TABEL UNTUK EDUQUEST PKWU
--
-- Jalankan seluruh skrip ini sekali di editor SQL Supabase Anda
-- (Dashboard Supabase -> SQL Editor -> New Query -> Run)
-- =========================================================================


-- =========================================================================
-- 1. PEMBUATAN TABEL (5 TABEL UTAMA)
-- =========================================================================

-- 1a. TABEL CLASSES (Menampung daftar kelas aktif)
CREATE TABLE IF NOT EXISTS public.classes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name text UNIQUE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1b. TABEL STUDENTS (Menampung akun murid terdaftar & kode unik)
CREATE TABLE IF NOT EXISTS public.students (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nis            text UNIQUE NOT NULL,
  student_name   text NOT NULL,
  class_name     text NOT NULL,
  attendance_num text NOT NULL,
  created_at     timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1c. TABEL QUIZZES (Menampung daftar pertanyaan kuis)
CREATE TABLE IF NOT EXISTS public.quizzes (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question       text NOT NULL,
  option_a       text NOT NULL,
  option_b       text NOT NULL,
  option_c       text NOT NULL,
  option_d       text NOT NULL,
  correct_answer text NOT NULL CHECK (correct_answer IN ('A', 'B', 'C', 'D')),
  type           text NOT NULL CHECK (type IN ('cognitive', 'interest')),
  category       text DEFAULT 'Umum' NOT NULL
);

-- 1d. TABEL STUDENT_RESULTS (Menampung rekap hasil pengerjaan kuis murid)
CREATE TABLE IF NOT EXISTS public.student_results (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name text NOT NULL,
  class_name   text NOT NULL,
  score        integer NOT NULL,
  remaining_hp integer NOT NULL DEFAULT 100,
  role         text NOT NULL DEFAULT 'Murid Active Learner',
  submit_at    timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1e. TABEL CLASS_ASSIGNMENTS (Menampung penugasan kuis aktif per kelas)
CREATE TABLE IF NOT EXISTS public.class_assignments (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name  text NOT NULL UNIQUE,
  category    text NOT NULL,
  assigned_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- =========================================================================
-- 2. HAK AKSES DAN KEBIJAKAN KEAMANAN (Row Level Security / RLS)
-- =========================================================================

-- Mengaktifkan RLS pada kelima tabel
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_assignments ENABLE ROW LEVEL SECURITY;

-- Kebijakan Akses untuk Tabel Classes (Membaca & Mengelola Kelas)
DROP POLICY IF EXISTS "Akses Publik Baca Classes" ON public.classes;
CREATE POLICY "Akses Publik Baca Classes" ON public.classes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Classes" ON public.classes;
CREATE POLICY "Akses Publik Kelola Classes" ON public.classes FOR ALL USING (true);

-- Kebijakan Akses untuk Tabel Students (Membaca & Mengelola Murid)
DROP POLICY IF EXISTS "Akses Publik Baca Students" ON public.students;
CREATE POLICY "Akses Publik Baca Students" ON public.students FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Students" ON public.students;
CREATE POLICY "Akses Publik Kelola Students" ON public.students FOR ALL USING (true);

-- Kebijakan Akses untuk Tabel Quizzes (Membaca & Mengelola Soal)
DROP POLICY IF EXISTS "Akses Publik Baca Quizzes" ON public.quizzes;
CREATE POLICY "Akses Publik Baca Quizzes" ON public.quizzes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Quizzes" ON public.quizzes;
CREATE POLICY "Akses Publik Kelola Quizzes" ON public.quizzes FOR ALL USING (true);

-- Kebijakan Akses untuk Tabel Class Assignments (Membaca & Mengelola Ujian Kelas)
DROP POLICY IF EXISTS "Akses Publik Baca Class Assignments" ON public.class_assignments;
CREATE POLICY "Akses Publik Baca Class Assignments" ON public.class_assignments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Class Assignments" ON public.class_assignments;
CREATE POLICY "Akses Publik Kelola Class Assignments" ON public.class_assignments FOR ALL USING (true);

-- Kebijakan Akses untuk Tabel Student Results (Membaca, Menambah, & Mengelola Nilai Murid)
DROP POLICY IF EXISTS "Akses Publik Tambah Student Results" ON public.student_results;
CREATE POLICY "Akses Publik Tambah Student Results" ON public.student_results FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Akses Publik Baca Student Results" ON public.student_results;
CREATE POLICY "Akses Publik Baca Student Results" ON public.student_results FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Student Results" ON public.student_results;
CREATE POLICY "Akses Publik Kelola Student Results" ON public.student_results FOR ALL USING (true);


-- =========================================================================
-- 3. DATA BAWAAN (SEEDED DATA)
-- =========================================================================

-- Data Bawaan Daftar Kelas
INSERT INTO public.classes (class_name) VALUES
('X MIPA 1'), ('X MIPA 2'), ('X IPS 1'), ('X IPS 2'),
('XI MIPA 1'), ('XI MIPA 2'), ('XI IPS 1'), ('XI IPS 2'),
('XII MIPA 1'), ('XII MIPA 2'), ('XII IPS 1'), ('XII IPS 2')
ON CONFLICT (class_name) DO NOTHING;

-- 4. PEMBERSIHAN SOAL DEMO BAWAAN (PURGE SEED DATA)
-- Perintah untuk menghapus kategori soal demo bawaan di Supabase
DELETE FROM public.quizzes WHERE category IN ('Sains & Logika', 'Eksplorasi Karakter', 'Lingkungan & Alam');
