-- =========================================================================
-- SKEMA SQL SUPABASE LENGKAP 5 TABEL UNTUK EDUQUEST PKWU
--
-- Jalankan seluruh skrip ini sekali di editor SQL Supabase Anda
-- (Dashboard Supabase -> SQL Editor -> New Query -> Run)
-- =========================================================================


-- =========================================================================
-- 1. PEMBUATAN TABEL (5 TABEL UTAMA)
-- =========================================================================

-- 1a. TABEL CLASSES (Menampung daftar kelas aktif)
CREATE TABLE IF NOT EXISTS public.classes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name text UNIQUE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1b. TABEL STUDENTS (Menampung akun murid terdaftar & kode unik)
CREATE TABLE IF NOT EXISTS public.students (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nis            text UNIQUE NOT NULL,
  student_name   text NOT NULL,
  class_name     text NOT NULL,
  attendance_num text NOT NULL,
  created_at     timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1c. TABEL QUIZZES (Menampung daftar pertanyaan kuis)
CREATE TABLE IF NOT EXISTS public.quizzes (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question       text NOT NULL,
  option_a       text NOT NULL,
  option_b       text NOT NULL,
  option_c       text NOT NULL,
  option_d       text NOT NULL,
  correct_answer text NOT NULL CHECK (correct_answer IN ('A', 'B', 'C', 'D')),
  type           text NOT NULL CHECK (type IN ('cognitive', 'interest')),
  category       text DEFAULT 'Umum' NOT NULL
);

-- 1d. TABEL STUDENT_RESULTS (Menampung rekap hasil pengerjaan kuis murid)
CREATE TABLE IF NOT EXISTS public.student_results (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name text NOT NULL,
  class_name   text NOT NULL,
  score        integer NOT NULL,
  remaining_hp integer NOT NULL DEFAULT 100,
  role         text NOT NULL DEFAULT 'Murid Active Learner',
  submit_at    timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1e. TABEL CLASS_ASSIGNMENTS (Menampung penugasan kuis aktif per kelas)
CREATE TABLE IF NOT EXISTS public.class_assignments (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name  text NOT NULL UNIQUE,
  category    text NOT NULL,
  assigned_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- =========================================================================
-- 2. HAK AKSES DAN KEBIJAKAN KEAMANAN (Row Level Security / RLS)
-- =========================================================================

-- Mengaktifkan RLS pada kelima tabel
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_assignments ENABLE ROW LEVEL SECURITY;

-- Kebijakan Akses untuk Tabel Classes (Membaca & Mengelola Kelas)
DROP POLICY IF EXISTS "Akses Publik Baca Classes" ON public.classes;
CREATE POLICY "Akses Publik Baca Classes" ON public.classes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Classes" ON public.classes;
CREATE POLICY "Akses Publik Kelola Classes" ON public.classes FOR ALL USING (true);

-- Kebijakan Akses untuk Tabel Students (Membaca & Mengelola Murid)
DROP POLICY IF EXISTS "Akses Publik Baca Students" ON public.students;
CREATE POLICY "Akses Publik Baca Students" ON public.students FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Students" ON public.students;
CREATE POLICY "Akses Publik Kelola Students" ON public.students FOR ALL USING (true);

-- Kebijakan Akses untuk Tabel Quizzes (Membaca & Mengelola Soal)
DROP POLICY IF EXISTS "Akses Publik Baca Quizzes" ON public.quizzes;
CREATE POLICY "Akses Publik Baca Quizzes" ON public.quizzes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Quizzes" ON public.quizzes;
CREATE POLICY "Akses Publik Kelola Quizzes" ON public.quizzes FOR ALL USING (true);

-- Kebijakan Akses untuk Tabel Class Assignments (Membaca & Mengelola Ujian Kelas)
DROP POLICY IF EXISTS "Akses Publik Baca Class Assignments" ON public.class_assignments;
CREATE POLICY "Akses Publik Baca Class Assignments" ON public.class_assignments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Class Assignments" ON public.class_assignments;
CREATE POLICY "Akses Publik Kelola Class Assignments" ON public.class_assignments FOR ALL USING (true);

-- Kebijakan Akses untuk Tabel Student Results (Membaca, Menambah, & Mengelola Nilai Murid)
DROP POLICY IF EXISTS "Akses Publik Tambah Student Results" ON public.student_results;
CREATE POLICY "Akses Publik Tambah Student Results" ON public.student_results FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Akses Publik Baca Student Results" ON public.student_results;
CREATE POLICY "Akses Publik Baca Student Results" ON public.student_results FOR SELECT USING (true);

DROP POLICY IF EXISTS "Akses Publik Kelola Student Results" ON public.student_results;
CREATE POLICY "Akses Publik Kelola Student Results" ON public.student_results FOR ALL USING (true);


-- =========================================================================
-- 3. DATA BAWAAN (SEEDED DATA)
-- =========================================================================

-- Data Bawaan Daftar Kelas
INSERT INTO public.classes (class_name) VALUES
('X MIPA 1'), ('X MIPA 2'), ('X IPS 1'), ('X IPS 2'),
('XI MIPA 1'), ('XI MIPA 2'), ('XI IPS 1'), ('XI IPS 2'),
('XII MIPA 1'), ('XII MIPA 2'), ('XII IPS 1'), ('XII IPS 2')
ON CONFLICT (class_name) DO NOTHING;

-- Data Bawaan Soal Kuis
INSERT INTO public.quizzes (question, option_a, option_b, option_c, option_d, correct_answer, type, category)
VALUES
(
  'Dalam metode ilmiah, setelah kita mengamati suatu fenomena atau masalah, langkah logis berikutnya yang paling tepat dilakukan adalah...',
  'Menarik kesimpulan final tanpa melakukan eksperimen atau pengumpulan data tambahan',
  'Menyusun hipotesis (dugaan sementara) yang masuk akal dan dapat diuji kebenarannya',
  'Menulis laporan ilmiah lengkap untuk langsung diterbitkan di jurnal pendidikan',
  'Mengabaikan fenomena tersebut jika hasilnya nanti diperkirakan tidak sesuai teori lama',
  'B',
  'cognitive',
  'Sains & Logika'
),
(
  'Saat bekerja dalam tim untuk membuat proyek pameran atau presentasi kelompok, peran apa yang paling nyaman Anda lakukan?',
  'Menjadi konseptor ide, menyusun rencana alur kerja, dan melakukan analisis awal (Planner)',
  'Menjadi praktisi teknis yang merakit alat, merapikan karya, atau memproses materi pengerjaan (Creator)',
  'Menjadi presenter utama yang menyampaikan gagasan di depan publik dengan percaya diri (Communicator)',
  'Menjadi koordinator kelompok yang memantau waktu, membagi tugas, dan menjaga disiplin tim (Coordinator)',
  'A',
  'interest',
  'Eksplorasi Karakter'
),
(
  'Berikut ini yang merupakan ciri utama dari sebuah argumen logis yang valid, kuat, dan tepercaya adalah...',
  'Menggunakan istilah ilmiah yang rumit dan panjang agar terlihat meyakinkan',
  'Didukung oleh fakta objektif, bukti data yang sahih, serta penalaran yang konsisten',
  'Berdasarkan kepada opini pribadi atau kepercayaan mayoritas semata tanpa bukti ilmiah',
  'Disampaikan dengan gaya bicara agresif agar lawan diskusi segera setuju',
  'B',
  'cognitive',
  'Sains & Logika'
),
(
  'Manakah di bawah ini yang merupakan contoh pemanfaatan sumber daya alam secara bijaksana dan berkelanjutan?',
  'Melakukan penebangan pohon di hutan lindung secara massal demi industri kayu lapis',
  'Menggunakan panel surya sebagai alternatif pembangkit energi ramah lingkungan',
  'Membuka lahan pertambangan mineral baru di dekat kawasan pemukiman warga',
  'Membakar sisa sampah rumah tangga secara terbuka di pekarangan pemukiman padat',
  'B',
  'cognitive',
  'Lingkungan & Alam'
),
(
  'Saat Anda diminta untuk melakukan presentasi di depan kelas, bagian manakah yang paling Anda sukai?',
  'Merancang kerangka materi, meriset data pendukung, dan membuat outline presentasi',
  'Membuat slide presentasi yang estetik, menambahkan gambar pendukung, dan merapikan visual',
  'Berdiri di depan berbicara langsung kepada audiens dan menjawab pertanyaan sulit melek',
  'Mengatur pembagian giliran bicara anggota tim agar presentasi berjalan tepat waktu',
  'C',
  'interest',
  'Eksplorasi Karakter'
),
(
  'Jika dalam menyelesaikan sebuah soal kuis atau tugas kelompok Anda mengalami kegagalan, bagaimana cara Anda menyikapinya?',
  'Menganalisis kesalahan data kognitif, meriset strategi belajar baru, dan menyusun peta konsep (Strategic Planner)',
  'Segera mencoba memodifikasi hasil praktik, membongkar kesalahan teknis, dan memperbaiki alat (Creator / Maker)',
  'Melatih cara mengomunikasikan materi, berdiskusi dengan guru, dan memperbaiki teknik penjelasan (Communicator)',
  'Mengevaluasi pembagian peran tim agar kerja sama berikutnya menjadi lebih solid dan disiplin (Operations Coordinator)',
  'D',
  'interest',
  'Eksplorasi Karakter'
)
ON CONFLICT DO NOTHING;
